version: '3'

services:

    db:
        image: 'rethinkdb:2.4.1-buster-slim'
        container_name: rethink_db
        ports:
            - 28015:28015
            - 8000:8080
        volumes:
            - '.:/data'
        restart: always
