version: '3'

services:

    db:
        image: 'rethinkdb:2.4.1-buster-slim'
        container_name: rethink_db
        ports:
            - 8080:8080
        volumes:
            - '.:/data'
        restart: always

    app:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        container_name: node
        volumes:
            - '.:/usr/src/app'
        ports:
            - 3000:3000
